package com.fashion.security;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.transaction.annotation.Transactional;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.*;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;

@RestController
@RequestMapping("/api/v1/customer")
@CrossOrigin(origins="${app.cors-origin:http://localhost:3000}")
public class CustomerAuthController {
 private final JdbcTemplate db; private final BCryptPasswordEncoder encoder=new BCryptPasswordEncoder();
//@Value("${app.jwt-secret:}") 
//private String jwtSecret;

 private final String jwtSecret;
 public CustomerAuthController(JdbcTemplate db, @Value("${app.jwt-secret:}") String jwtSecret){this.db=db;this.jwtSecret=jwtSecret;}
 private void configured(){if(jwtSecret==null||jwtSecret.length()<32)throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"Set JWT_SECRET to a random secret of at least 32 characters");}
 @PostMapping("/register") public Map<String,Object> register(@RequestBody Register r){configured();if(r.name==null||r.name.isBlank()||r.email==null||!r.email.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$")||r.password==null||r.password.length()<10)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Name, valid email and password (10+ characters) are required");UUID id=UUID.randomUUID();try{db.update("INSERT INTO customer_users(id,full_name,email,phone,password_hash,role) VALUES(?,?,?,?,?,'CUSTOMER')",id,r.name.trim(),r.email.trim().toLowerCase(Locale.ROOT),r.phone,encoder.encode(r.password));}catch(Exception e){throw new ResponseStatusException(HttpStatus.CONFLICT,"An account with this email may already exist");}return tokenResponse(id,r.name,r.email,"CUSTOMER");}
 @PostMapping("/login") public Map<String,Object> login(@RequestBody Login r){configured();List<Map<String,Object>> rows=db.queryForList("SELECT id,full_name,email,password_hash,role,enabled FROM customer_users WHERE lower(email)=lower(?)",r.email);if(rows.isEmpty()||!encoder.matches(Objects.toString(r.password,""),Objects.toString(rows.get(0).get("password_hash"),""))||!Boolean.TRUE.equals(rows.get(0).get("enabled")))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid email or password");var u=rows.get(0);return tokenResponse((UUID)u.get("id"),Objects.toString(u.get("full_name")),Objects.toString(u.get("email")),Objects.toString(u.get("role")));}
 @GetMapping("/addresses") public List<Map<String,Object>> addresses(@RequestHeader("Authorization") String auth){UUID uid=subject(auth);return db.queryForList("SELECT id,recipient_name AS \"recipientName\",phone,address_line1 AS \"addressLine1\",address_line2 AS \"addressLine2\",city,state,postal_code AS \"postalCode\",country,address_type AS \"addressType\",is_default AS \"default\" FROM customer_addresses WHERE user_id=? ORDER BY is_default DESC,created_at DESC",uid);}
 @PostMapping("/addresses") @Transactional public Map<String,Object> addAddress(@RequestHeader("Authorization") String auth,@RequestBody Address a){UUID uid=subject(auth);db.queryForObject("SELECT id FROM customer_users WHERE id=? FOR UPDATE",UUID.class,uid);validateAddress(a);String phone=a.phone.trim().replaceAll("\\s+","");String line1=a.addressLine1.trim();String line2=blank(a.addressLine2)?null:a.addressLine2.trim();String city=a.city.trim();String state=a.state.trim();String postal=a.postalCode.trim().toUpperCase(Locale.ROOT);String country=blank(a.country)?"IN":a.country.trim().toUpperCase(Locale.ROOT);String recipient=a.recipientName.trim();String type=addressType(a.addressType);List<Map<String,Object>> duplicates=db.queryForList("SELECT id FROM customer_addresses WHERE user_id=? AND lower(btrim(recipient_name))=lower(btrim(?)) AND lower(btrim(phone))=lower(btrim(?)) AND lower(btrim(address_line1))=lower(btrim(?)) AND lower(btrim(coalesce(address_line2,'')))=lower(btrim(coalesce(?,''))) AND lower(btrim(city))=lower(btrim(?)) AND lower(btrim(state))=lower(btrim(?)) AND upper(btrim(postal_code))=upper(btrim(?)) AND upper(country)=upper(?) ORDER BY created_at DESC LIMIT 1",uid,recipient,phone,line1,line2,city,state,postal,country);if(!duplicates.isEmpty()){UUID existing=(UUID)duplicates.get(0).get("id");if(a.isDefault){db.update("UPDATE customer_addresses SET is_default=false WHERE user_id=?",uid);db.update("UPDATE customer_addresses SET is_default=true,address_type=? WHERE id=? AND user_id=?",type,existing,uid);}return Map.of("id",existing,"saved",true,"duplicate",true);}
 if(a.isDefault)db.update("UPDATE customer_addresses SET is_default=false WHERE user_id=?",uid);UUID id=UUID.randomUUID();db.update("INSERT INTO customer_addresses(id,user_id,recipient_name,phone,address_line1,address_line2,city,state,postal_code,country,is_default,address_type) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING",id,uid,recipient,phone,line1,line2,city,state,postal,country,a.isDefault,type);if(db.queryForObject("SELECT count(*) FROM customer_addresses WHERE id=?",Integer.class,id)==0){List<Map<String,Object>> matched=db.queryForList("SELECT id FROM customer_addresses WHERE user_id=? AND lower(btrim(recipient_name))=lower(btrim(?)) AND lower(btrim(phone))=lower(btrim(?)) AND lower(btrim(address_line1))=lower(btrim(?)) AND lower(btrim(coalesce(address_line2,'')))=lower(btrim(coalesce(?,''))) AND lower(btrim(city))=lower(btrim(?)) AND lower(btrim(state))=lower(btrim(?)) AND upper(btrim(postal_code))=upper(btrim(?)) AND upper(country)=upper(?) ORDER BY created_at DESC LIMIT 1",uid,recipient,phone,line1,line2,city,state,postal,country);if(matched.isEmpty())throw new ResponseStatusException(HttpStatus.CONFLICT,"This address could not be saved because it conflicts with an existing record.");id=(UUID)matched.get(0).get("id");if(a.isDefault)db.update("UPDATE customer_addresses SET is_default=true,address_type=? WHERE id=? AND user_id=?",type,id,uid);}return Map.of("id",id,"saved",true);}
 @PutMapping("/addresses/{id}") @Transactional public Map<String,Object> updateAddress(@RequestHeader("Authorization") String auth,@PathVariable UUID id,@RequestBody Address a){UUID uid=subject(auth);db.queryForObject("SELECT id FROM customer_users WHERE id=? FOR UPDATE",UUID.class,uid);validateAddress(a);String phone=a.phone.trim().replaceAll("\\s+","");String country=blank(a.country)?"IN":a.country.trim().toUpperCase(Locale.ROOT);if(a.isDefault)db.update("UPDATE customer_addresses SET is_default=false WHERE user_id=?",uid);int changed=db.update("UPDATE customer_addresses SET recipient_name=?,phone=?,address_line1=?,address_line2=?,city=?,state=?,postal_code=?,country=?,address_type=?,is_default=? WHERE id=? AND user_id=?",a.recipientName.trim(),phone,a.addressLine1.trim(),blank(a.addressLine2)?null:a.addressLine2.trim(),a.city.trim(),a.state.trim(),a.postalCode.trim().toUpperCase(Locale.ROOT),country,addressType(a.addressType),a.isDefault,id,uid);if(changed==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Address not found");return Map.of("id",id,"saved",true);}
 @DeleteMapping("/addresses/{id}") @Transactional public Map<String,Object> deleteAddress(@RequestHeader("Authorization") String auth,@PathVariable UUID id){UUID uid=subject(auth);db.queryForObject("SELECT id FROM customer_users WHERE id=? FOR UPDATE",UUID.class,uid);Boolean wasDefault=db.query("SELECT is_default FROM customer_addresses WHERE id=? AND user_id=?",rs->rs.next()?rs.getBoolean(1):null,id,uid);if(wasDefault==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Address not found");db.update("DELETE FROM customer_addresses WHERE id=? AND user_id=?",id,uid);if(wasDefault)db.update("UPDATE customer_addresses SET is_default=true WHERE id=(SELECT id FROM customer_addresses WHERE user_id=? ORDER BY created_at DESC,id LIMIT 1)",uid);return Map.of("deleted",true);}
 private void validateAddress(Address a){if(a==null||blank(a.recipientName)||blank(a.phone)||blank(a.addressLine1)||blank(a.city)||blank(a.state)||blank(a.postalCode))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Name, phone, street address, city, state and PIN code are required.");if(a.recipientName.trim().length()>160||a.phone.trim().length()>20||a.addressLine1.trim().length()>240||(!blank(a.addressLine2)&&a.addressLine2.trim().length()>240)||a.city.trim().length()>120||a.state.trim().length()>120||a.postalCode.trim().length()>12)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"One or more address fields exceed the allowed length.");if(!a.postalCode.trim().matches("[A-Za-z0-9 -]{3,12}"))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Enter a valid postal code.");if(!blank(a.country)&&!a.country.trim().matches("(?i)[A-Z]{2}"))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Choose a valid two-letter country code.");}
 private String addressType(String value){String type=blank(value)?"HOME":value.trim().toUpperCase(Locale.ROOT);if(!Set.of("HOME","WORK","OTHER").contains(type))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Choose Home, Work or Other for this address.");return type;}
 public UUID subject(String auth){configured();try{String[] p=auth.replaceFirst("(?i)^Bearer ","").split("\\.");if(p.length!=3||!MessageDigest.isEqual(sign(p[0]+"."+p[1]).getBytes(StandardCharsets.UTF_8),p[2].getBytes(StandardCharsets.UTF_8)))throw new Exception();String json=new String(Base64.getUrlDecoder().decode(p[1]),StandardCharsets.UTF_8);String sub=json.replaceAll(".*\\\"sub\\\":\\\"([^\\\"]+)\\\".*","$1");long exp=Long.parseLong(json.replaceAll(".*\\\"exp\\\":([0-9]+).*","$1"));if(Instant.now().getEpochSecond()>exp)throw new Exception();return UUID.fromString(sub);}catch(Exception e){throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid or expired bearer token");}}
 public boolean isAdmin(String auth){ UUID id=subject(auth); String role=db.queryForObject("SELECT role FROM customer_users WHERE id=? AND enabled=true",String.class,id); return "ADMIN".equals(role); }
 private Map<String,Object> tokenResponse(UUID id,String name,String email,String role){long exp=Instant.now().getEpochSecond()+86400;String h=enc("{\"alg\":\"HS256\",\"typ\":\"JWT\"}");String p=enc("{\"sub\":\""+id+"\",\"email\":\""+email+"\",\"role\":\""+role+"\",\"exp\":"+exp+"}");return Map.of("token",h+"."+p+"."+sign(h+"."+p),"tokenType","Bearer","expiresIn",86400,"customer",Map.of("id",id,"name",name,"email",email,"role",role));}
 private String sign(String s){try{Mac m=Mac.getInstance("HmacSHA256");m.init(new SecretKeySpec(jwtSecret.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));return Base64.getUrlEncoder().withoutPadding().encodeToString(m.doFinal(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private String enc(String s){return Base64.getUrlEncoder().withoutPadding().encodeToString(s.getBytes(StandardCharsets.UTF_8));}private boolean blank(String s){return s==null||s.isBlank();}
 public static class Register{public String name,email,phone,password;} public static class Login{public String email,password;} public static class Address{public String recipientName,phone,addressLine1,addressLine2,city,state,postalCode,country,addressType;public boolean isDefault;}
}
